default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.21.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: name-tests-test
        args:
          - --pytest
        exclude: tests
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: detect-private-key
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.5.1"
    hooks:
      - id: prettier
        exclude: ^tests|^.idea|^migrations|^.git
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.5.0"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: ^tests|^docs|^.venv|^.git|\.json$
        additional_dependencies:
          - tomli
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.6.0
    hooks:
      - id: pydoclint
        args:
          [
            --style=google,
            --check-return-types=False,
            --arg-type-hints-in-docstring=False,
          ]
